version: '3'
services:
  etcd:
    container_name: etcd
    image: bitnami/etcd:3.3
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
    volumes:
      - ./data:/bitnami/etcd
    ports:
      - "2379:2379"
