version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      discovery.type: single-node
    volumes:
      # - ./config:/usr/share/elasticsearch/config
      - ./data:/usr/share/elasticsearch/data
