version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.9.4
    environment:
      # MARIADB_USER: admin
      # MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
