version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
