version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image:  zookeeper:3.5
    ports:
      - "2181:2181"
    volumes:
      - ./data/zk/data:/data
      - ./data/zk/datalog:/datalog
      - ./data/zk/logs:/logs
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'wurstmeister/kafka:2.13-2.8.1'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ADVERTISED_HOST_NAME=192.168.0.100  # need change to host IP
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.100:9092 # need change to host IP
    volumes:
      - ./data/kafka/kafka:/kafka
      - ./data/kafka/config:/opt/kafka/config
    depends_on:
      - zookeeper
